runtime: python37
instance_class: F4

env_variables:
  FLASK_APP: app.py
  APP_SETTINGS: config.DevelopmentConfig
  CLOUD_SQL_URI: mysql://root:keonp2@35.226.133.103/project_db
  SPACY_WARNING_IGNORE: W007
